name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATCH_VIEWING_DASHBOARD }}'
          channelId: live
          projectId: match-viewing-dashboard
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
